@startuml
class AbstractObject <<Class>>
{
+ str name
+ str type
+ str origin
+ List<str> usingNS
+ AbstractObjectLanguage objectLanguage
+ List<str> linkedGenericTypes
+None Constructor(str name, str origin)
+None addUsingNamespace(str namespace)
}
enum AbstractObjectLanguage <<Enum>>
{
Unknown
CPP
Python
Java
Kotlin
}
AbstractObject ..|> AbstractObjectLanguage
@enduml
