@startuml
class KotlinAnalyzer <<Class>>
{
+ List<str> globalImports
+None Constructor()
+List<AbstractObject> analyze(str rootDir, str path)
+None handleClass(List<AbstractObject> abstractObjects, str path, str currentNS, Union<kopyt::ClassDeclaration,kopyt::InterfaceDeclaration> klass)
+None handleParent(AbstractClass abstraction, kopyt::DelegationSpecifiers item)
+None handleConstuctor(AbstractClass abstraction, Union<kopyt::PrimaryConstructor,kopyt::SecondaryConstructor> item, bool isPrimary)
+None handleProperty(AbstractClass abstraction, kopyt::PropertyDeclaration item, bool isStatic)
+None handleMethod(AbstractClass abstraction, kopyt::FunctionDeclaration item, bool isStatic)
+None handleEnum(List<AbstractObject> abstractObjects, str path, str currentNS, kopyt::EnumDeclaration enum)
+None handleFunction(List<AbstractObject> abstractObjects, str path, str currentNS, kopyt::FunctionDeclaration function)
+str deduceVisibility(Any item)
+str deduceTypeFromExpression(str expression)
+str deduceType(str type)
}
class Analyzer <<Class>>
{
+ Any logger
+None Constructor(str name)
+List<AbstractObject> analyze(str rootDir, str path)
}
class AbstractObject <<Class>>
{
+ str name
+ str type
+ str origin
+ AbstractObjectLanguage language
+ List<str> usingNS
+ List<str> linkedGenericTypes
+None Constructor(str name, str origin)
+None addUsingNamespace(str namespace)
}
class ClassDeclaration <<External>>
class InterfaceDeclaration <<External>>
class Union <<External>>
class AbstractClass <<Class>>
{
+ str namespace
+ str type
+ List<Tuple<str,str,str>> members
+ List<Tuple<str,str,List<Tuple<str,str>>,str>> methodes
+ List<Tuple<str,str,str>> parents
+ List<str> linkedGenericTypes
+None Constructor(str name, str namespace, str origin)
+None addGenericType(str genType)
+None addMember(str type, str name, str visibility)
+bool hasMember(str name)
+None addMethod(str returnType, str name, List<Tuple<str,str>> parameters, str visibility)
+None addParent(str completetype, str name, str visibility)
+List<str> getLinkedTypes()
-bool isPotentialClassName(str type)
-List<str> getDependanceFromType(str type)
-List<str> splitTypes(Any decl)
+str getFullName()
-str cleanLanguageArtifacts(str type)
-List<str> removeNonObjectTypes(List<str> typeList)
+bool isParent(AbstractClass klass)
+None print()
}
class DelegationSpecifiers <<External>>
class PrimaryConor <<External>>
class SecondaryConor <<External>>
class PropertyDeclaration <<External>>
class FunctionDeclaration <<External>>
class EnumDeclaration <<External>>
KotlinAnalyzer --|> Analyzer
KotlinAnalyzer ..|> AbstractObject
KotlinAnalyzer ..|> ClassDeclaration
KotlinAnalyzer ..|> InterfaceDeclaration
KotlinAnalyzer ..|> Union
KotlinAnalyzer ..|> AbstractClass
KotlinAnalyzer ..|> DelegationSpecifiers
KotlinAnalyzer ..|> PrimaryConor
KotlinAnalyzer ..|> SecondaryConor
KotlinAnalyzer ..|> PropertyDeclaration
KotlinAnalyzer ..|> FunctionDeclaration
KotlinAnalyzer ..|> EnumDeclaration
@enduml
