@startuml
class Analyzer <<Class>>
{
+ Any logger
+None Constructor(str name)
+List<AbstractObject> analyze(str rootDir, str path)
}
class AbstractObject <<Class>>
{
+ str name
+ str type
+ str origin
+ List<str> usingNS
+ AbstractObjectLanguage objectLanguage
+ List<str> linkedGenericTypes
+None Constructor(str name, str origin)
+None addUsingNamespace(str namespace)
}
Analyzer ..|> AbstractObject
@enduml
