@startuml
class UiFileDispatcherListener <<Class>>
{
+None notifyAnalyzing(str file)
+None notifyAnalysisEnd()
}
class UiLink <<Class>>
{
+ SocketIO socketio
+None Constructor()
+None setSocketIO(SocketIO socketio)
}
UiFileDispatcherListener --|> UiLink
@enduml
