@startuml
class AbstractFunction <<Class>>
{
+ str namespace
+ str type
+ str returnType
+ List<Tuple<str,str>> parameters
+ str doxygen
+ List<str> linkedGenericTypes
+None Constructor(str name, str origin, str returnType, List<Tuple<str,str>> parameters, str namespace, str doxygen)
+None addGenericType(str genType)
+None print()
+str getFullDef()
}
class AbstractObject <<Class>>
{
+ str name
+ str type
+ str origin
+ List<str> usingNS
+ AbstractObjectLanguage objectLanguage
+ List<str> linkedGenericTypes
+None Constructor(str name, str origin)
+None addUsingNamespace(str namespace)
}
AbstractFunction --|> AbstractObject
@enduml
