classDiagram
class CustomCppHeader {
<<Class>>
+is_enum_namestack(Any nameStack) bool
+is_property_namestack(Any nameStack) bool
+is_method_namestack(Any stack) bool
}
class CppHeader
<<External>> CppHeader
CustomCppHeader ..> CppHeader
