# This is a basic workflow to help you get started with Actions

name: CI - Quality

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "quality-check"
  quality-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Initialize Python 3.7
        uses: actions/setup-python@v1
        with:
            python-version: 3.7
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install flake8
      - name: Lint python with flake8
        run: |
            # stop the build if there are Python syntax errors or undefined names
            flake8 ./pycodeanalyzer --count --select=E9,F63,F7,F82 --show-source --statistics
            # exit-zero treats all errors as warnings.
            flake8 ./pycodeanalyzer --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint JS with StandardJs
        uses: iCrawl/action-eslint@v1

