# This is a basic workflow to help you get started with Actions

name: TestPackage

# Allows you to run this workflow manually from the Actions tab
on:
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            ref: stable

      - name: Initialize Python 3.7
        uses: actions/setup-python@v1
        with:
            python-version: 3.7

      - name: Build binary wheel and a source tarball
        run: python setup.py sdist
  publish-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job only on release branch
    steps:
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
            password: ${{ secrets.test_pypi_password }}
            repository_url: https://test.pypi.org/legacy/
      - name: Verify packet on TestPyPI
        run: |
          sed -i -E -e "s?version=\"(.*)\"?version=\"\1-$(git rev-parse --short HEAD)\"?g" setup.py
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pycodeanalyzer
